### ISSUE TITLE
Frame not generated with the screenshot

### ISSUE THREAD

**Issue by fvisticot** [mmcc007/screenshots#1]
ImageMagick is available on my MAC.

I have added screenshots to my integration test (test_driver directory)

launch the test:
flutter drive --target=test_driver/my_app.dart

The screenshot is available in the /tmp/screenshots directory

BUT
No frame of the screenshot with iOS device
The directory /tmp/ios is empty (should have framed images here)

config file:
```
# Screen capture tests
tests:
- test_driver/my_app.dart

# Interim location of screenshots from tests before processing
staging: /tmp/screenshots

# A list of locales supported in app
locales:
- en-US
#  - de-DE

# A list of devices to emulate
devices:
  ios:
  - iPhone X
  - iPhone 7 Plus
  #- iPad Pro (12.9-inch) (2nd generation)
  #   "iPhone 6",
  #   "iPhone 6 Plus",
  #   "iPhone 5",
  #   "iPhone 4s",
  #   "iPad Retina",
  #   "iPad Pro"
  android:
  #- Nexus 5X

# Frame screenshots
frame: true

## final destination of processed screenshots
dest:
  ios: /tmp/ios
  android: /tmp/android
```

**Comment by mmcc007** [comment]
To launch screenshots use:
```
screenshots
```
Per the readme the only destination is:
```
android/fastlane/metadata/android/en-US/images
ios/fastlane/screenshots/en-US
```
This is because screenshots is intended to work with fastlane

See currently supported screens in [devices.yaml](https://github.com/mmcc007/screenshots/blob/master/lib/resources/devices.yaml). iPhoneX screen is not among them.

Hope this helps!

**Comment by fvisticot** [comment]
Tx, it is working after installing pub 
Did you plan 
- to add extra devices for iOS ? would be fine to have iPhoneX screenshots for Appstore.
- to add text / description

**Comment by mmcc007** [comment]
Great!
I notice some don't have `pub` installed sometimes (it's included in flutter, BTW). 

There's nothing in code to prevent adding more devices (AFAIK). Just need the artwork for clean status bars for each screen. Artwork from frames for all devices (ios and android) is already available. 

When I can locate artwork for status bars preferably in sketch (or make my own artwork in sketch I guess), I can add more devices.

Adding text/description is another kettle of fish. It basically requires adding another config file and calls to imageMagick. Not sure how much demand there is for that.

In the meantime, there's nothing to prevent taking a screenshot and adding text and other effects in another custom step.
