### ISSUE TITLE
travis config :: version solving failed

### ISSUE THREAD

**Issue by zanuka** [mmcc007/screenshots#10]
I'm currently trying to get this to work in our Travis CI pipeline, based on the working [example config](https://travis-ci.com/mmcc007/screenshots/builds/102852032/config)

Have attached screenshot. 

![screen shot 2019-03-05 at 10 38 24 am](https://user-images.githubusercontent.com/202134/53764929-83e1b500-3f33-11e9-9b63-e879e56b8935.png)

**Comment by zanuka** [comment]
I think this was my issue, I forgot `pub global activate screenshots` and instead had your original `- pub global activate --source path .`

**Comment by mmcc007** [comment]
yes, and keep in mind that, with that change, you are using the currently released version of Screenshots.
