### ISSUE TITLE
Config does not respect the configuration path passed as a command line argument

### ISSUE THREAD

**Issue by orestesgaolin** [mmcc007/screenshots#108]
While running screenshots on Linux with Android SDK i get following error:

```
Starting flutter daemon...
Unhandled exception:
RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:145:60)
#1      iosDevices (package:screenshots/src/daemon_client.dart:193:23)
#2      DaemonClient.start (package:screenshots/src/daemon_client.dart:39:21)
<asynchronous suspension>
#3      run (package:screenshots/src/run.dart:38:22)
<asynchronous suspension>
#4      main (file:///root/.pub-cache/hosted/pub.dartlang.org/screenshots-1.3.0/bin/main.dart:85:9)
<asynchronous suspension>
#5      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

I have two configuration files: `configuration_android.yaml` for Linux, and `configuration_ios.yaml` for macOS.

iOS:
```
devices:
  ios:
     iPhone Xs Max:
     iPhone 8 Plus:
```

Android:
```
devices:
  android:
    Nexus 6P:
```

The problem is that when I run:
`screenshots --config=screenshots_android.yaml -f tst` or `screenshots -c screenshots_android.yaml -f tst` on Linux `screenshots` tries to use `screenshots.yaml` file instead of `screenshots_android.yaml` and perhaps fallbacks to iOS file? Linux doesn't support iOS simulators and thus we have exception.

I think this is because `Config()` has `kConfigFileName` as a default parameter.

**Comment by mmcc007** [comment]
I added some code to run on mac, linux and windows. It is not released yet. To try it:
```
pub global activate --source git https://github.com/mmcc007/screenshots.git
```

Let me know if it works.

**Comment by orestesgaolin** [comment]
Thanks, it seems it's ok now.
Could we for instance ignore text capitalization? My emulator is visible as `pixel_3_xl` and I would like to be able to run it even when I call it `Pixel 3 XL` in `screens.yaml`.

**Comment by mmcc007** [comment]
Apparently some device names are case sensitive. For example `iPhone 6S Plus` and `iPhone 6s Plus`, and `iPhone XS` and `iPhone Xs`. May also be happening for android devices. So perhaps this feature may not be a good fit?

**Comment by orestesgaolin** [comment]
Ok, so if I would like to add e.g. `PIxel 3 XL`, then I should add in README.md that emulator must be named exactly `Pixel 3 XL`, am I right?

It seems that I almost figured out the proper scaling. Take a look:
![framed_screenshot](https://user-images.githubusercontent.com/16854239/64000377-e5ab6200-cb05-11e9-8911-64bdc1d34dd9.png)

**Comment by mmcc007** [comment]
> Ok, so if I would like to add e.g. Pixel 3 XL, then I should add in README.md that emulator must be named exactly Pixel 3 XL, am I right?

The validator will catch any mis-matches, give an error message and stop the run.

Nice! The scaling looks pretty close. There may be a proportioning issue with the original status bar image (looks a bit thin?). Can take a closer look after installing emulator for Pixel 3 XL.

**Comment by orestesgaolin** [comment]
Yes, the default 1440 status bar is incorrect. I'll try to create a proper one in my spare time. Are tests required when submitting such changes?

**Comment by mmcc007** [comment]
No code, so currently no tests. Will probably use frame.dart to generate the framed screenshot and just compare to emulator. 

Will track new screen in #107
