### ISSUE TITLE
Verbose logging [Feature request]

### ISSUE THREAD

**Issue by orestesgaolin** [mmcc007/screenshots#109]
I'd love to set verbose logging during execution e.g. via `-v`/`--verbose` flags.

**Comment by mmcc007** [comment]
That's in the works. Installed logging from the flutter tools project and will be replacing all print statements.

**Comment by mmcc007** [comment]
Added flutter-like verbose mode.
Try it out with:
```
pub global activate --source git https://github.com/mmcc007/screenshots.git
cd <your project>
screenshots -v
```
