### ISSUE TITLE
Update intl dependency

### ISSUE THREAD

**Issue by cbenhagen** [mmcc007/screenshots#124]
https://github.com/flutter/flutter/pull/39932 updated to 0.16.0

Maybe add `intl: ">=0.15.0 <1.0.0"` to prevent issues like this in the future.

**Comment by mmcc007** [comment]
Thanks for the tip

**Comment by joeblew99** [comment]
i had to pump it to 16 to make it fine

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0

I am on flutter master.

**Comment by mmcc007** [comment]
@joeblew99 are u on v2.0.2+1? To upgrade
```
pub global activate screenshots
pub global list
```

**Comment by joeblew99** [comment]
@mmcc007  i was always on version: 2.0.2+1

If i recall, i did the ```pub global activate screenshots``` first, hit the version dependency issue, bumped it to 0.16.0, and then everything ran correctly.
