### ISSUE TITLE
Support the latest flutter version 1.10.x

### ISSUE THREAD

**Issue by rockingdice** [mmcc007/screenshots#127]
It complains that screenshots cannot support the latest version. But I think it's just a version requirement change. Please support the latest version of flutter.

**Comment by mmcc007** [comment]
Thanks for the heads-up.

Screenshots usually follows the stable channel release which is currently on v1.7.8+hotfix.4. I tried switching to the beta channel (using `flutter channel beta`) which is currently on v1.9.1+hotfix.2 (3 days ago) and it ran normally.

I'm guessing the version you are running on is probably in the master channel and is not yet ready for production.

Does this sound correct?

**Comment by rockingdice** [comment]
Yes, it's correct. I think I may change back to the beta channel. Thank you.
