### ISSUE TITLE
running `screenshots` with Simulator app closed

### ISSUE THREAD

**Issue by zanuka** [mmcc007/screenshots#13]
was able to reproduce on iMac and MacBook Air, both running XCode 10.1, MacOS 10.14.3

I could run `screenshots` just fine w/ the following config:
```
devices:
  ios:
    - iPhone X
    - iPhone 7 Plus
    - iPad Pro (12.9-inch) (2nd generation)
```

but **only** with the **Simulator** app opened, and all devices closed. 

if I try to run with the **Simulator** app closed, I get driver test failures that look like this:

```
00:22 +11 -1: smoke test DashboardScreen > take screenshot [E]
  DriverError: Error in Flutter application: Timeout while executing waitUntilNoTransientCallbacks: TimeoutException after 0:00:05.000000: Future not completed
  #0      FlutterDriverExtension.call (package:flutter_driver/src/extension/extension.dart:180:31)
  <asynchronous suspension>
  #1      BindingBase.registerServiceExtension.<anonymous closure> (package:flutter/src/foundation/binding.dart:438:32)
  <asynchronous suspension>
  #2      _runExtension (dart:developer/runtime/libdeveloper.dart:86:23)

  Original error: null
  Original stack trace:
  null

  package:flutter_driver/src/driver/driver.dart 440:7   FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/future_impl.dart 22:43                     _Completer.completeError
  dart:async/runtime/libasync_patch.dart 40:18          _AsyncAwaitCompleter.completeError
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
  package:flutter_driver/src/driver/driver.dart         FlutterDriver._sendCommand
  package:flutter_driver/src/driver/driver.dart 490:11  FlutterDriver.waitUntilNoTransientCallbacks
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1053:19                          _CustomZone.registerUnaryCallback
  dart:async/runtime/libasync_patch.dart 77:23          _asyncThenWrapperHelper
  package:test_api/src/backend/declarer.dart            Declarer.test.<fn>.<fn>.<fn>
  package:test_api/src/backend/invoker.dart 249:15      Invoker.waitForOutstandingCallbacks.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1045:19                          _CustomZone.registerCallback
  dart:async/zone.dart 962:22                           _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 52:45                           new Timer
  dart:async/timer.dart 87:9                            Timer.run
  dart:async/future.dart 174:11                         new Future
  package:test_api/src/backend/invoker.dart 398:11      Invoker._onRun.<fn>.<fn>.<fn>
```

running `flutter driver --target=test_driver/smoke.dart` from CLI 

generates `No devices found.` which I had expected if the Simulator app is closed.

**Comment by mmcc007** [comment]
Not able to reproduce locally. But was able to start a test from the command line without running Simulator.app.

To start a test from the command line without Simulator.app running, make sure nothing is running with:
```
$ flutter devices
No devices detected.
$ ps ax | grep Simulator.app
```
 and try:
```
xcrun simctl list devices
xcrun simctl boot <device id>
```
Flutter should find the device and be able to run test without Simulator.app running:
```
flutter devices
ps ax | grep Simulator.app
flutter driver --target=test_driver/smoke.dart
```
If test runs, then it should run in Screenshots. 

If test reproduces this problem then it is something specific to the machine (I'm guessing).

As you mentioned, this smoke test runs on Travis on simulator?

**Comment by zanuka** [comment]
Thanks for looking into this, it must be something on my machine / local config. It hadn't run on Travis because the app just kept failing to start. I'll spend more time creating a pipeline on a basic flutter app scaffold and putting all the pieces together, test some more.

**Comment by zanuka** [comment]
and these appear after every test:
```
01:20 +11 -2: smoke test LogbookScreen > take screenshot
[info ] FlutterDriver: >>> {command: waitUntilNoTransientCallbacks}
[warning] FlutterDriver: waitUntilNoTransientCallbacks message is taking a long time to complete...
```

note: this is with the Simulator.app closed, they all work when it is open. curious what version of XCode you are running.

**Comment by zanuka** [comment]
figured out the issue --- the driver tests fail if I don't manually click simulator permissions that appear on certain tests like 'Always Allow' location and 'Accept Notifications' 

so we're pulling the plug on screenshots Travis integration for now until new strategy on smoke tests are decided upon

**Comment by mmcc007** [comment]
OK, ... interested in how it turns out... 

BTW: it's possible to configure the timeout on waitUntilNoTransientCallbacks
(I added a demo to #14 see: https://travis-ci.org/mmcc007/screenshots/builds/502300580 for travis run )

**Comment by zanuka** [comment]
I missed this comment, thanks for that demo. just haven't had much time to focus on this lately.
