### ISSUE TITLE
Issue: Cannot find executable for flutter

### ISSUE THREAD

**Issue by k00na** [mmcc007/screenshots#135]
Im trying to run screenshots (version 2.0.2+1.) on macOS Mojave (Version 10.14.5)... 

After running "pub global activate screenshots" I get this warning: 

```
Warning: Pub installs executables into $HOME/.pub-cache/bin, which is not on your path.
You can fix that by adding this to your shell's config file (.bashrc, .bash_profile, etc.):

export PATH="$PATH":"$HOME/.pub-cache/bin"
```

Then I do as suggested, export the path and run "screenshots" in terminal and this is the error I get: 

```
Starting flutter daemon...                                             ⣽Unhandled exception:
**Invalid argument(s): Cannot find executable for flutter.**
#0      _getExecutable (package:process/src/interface/local_process_manager.dart:127:5)
#1      LocalProcessManager.start (package:process/src/interface/local_process_manager.dart:43:30)
#2      runCommand (package:tool_base/src/base/process.dart:117:25)
#3      DaemonClient.start (package:screenshots/src/daemon_client.dart:33:24)
<asynchronous suspension>
#4      runScreenshots (package:screenshots/src/run.dart:79:22)
<asynchronous suspension>
#5      screenshots.<anonymous closure> (package:screenshots/src/run.dart:45:14)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#12     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#13     screenshots (package:screenshots/src/run.dart:44:12)
<asynchronous suspension>
#14     main (file:///Users/igor/.pub-cache/hosted/pub.dartlang.org/screenshots-2.0.2+1/bin/main.dart:102:25)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)

```
I then also try to export flutter path as suggested in the docs:
`export PATH="<path to flutter installation directory>/bin/cache/dart-sdk/bin:$PATH"`

But it doesnt work. Otherwise my Flutter setup works perfectly and "flutter doctor" doesnt print out any issues, all seems to be well. 

Any idea or suggestions on how to solve this?

**Comment by mmcc007** [comment]
That's a strange one. 

Are you running 'screenshots' from the same command line session you are running 'flutter doctor'?

**Comment by mcoolidge** [comment]
I have the same issue running from the same session as screenshots.

**Comment by mcoolidge** [comment]
I was able to fix on my machine. Previously I had the path include ~ but I switched to $HOME. This implies its a PATH related problem.

**Comment by mmcc007** [comment]
Currently the code to create a process does not run in the OS's default shell and AFAIK, '~' is specific to the shell (like sh or bash, or whatever POSIX-like shell you are running on macOS or linux). 

The fix for this is probably  either to document against using '~' in place of $HOME or modify code to run a process in the default shell.

**Comment by mmcc007** [comment]
Added check for finding flutter at startup.
Try it out using:
```
git clone  https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #135_flutter_path
pub global activate --source path .
```

**Comment by Niek** [comment]
FYI I had the same issue on 2.1.1 - changing ``~`` to ``$HOME`` fixed the problems for me.

**Comment by mmcc007** [comment]
@Niek Did screenshots catch this (before you fixed it)?

**Comment by Niek** [comment]
> @Niek Did screenshots catch this (before you fixed it)?

Yes, I get this error if I change it back to ``~``:
```bash
$ export PATH=$(echo $PATH | sed 's/\/Users\/niek/~/g')
$ flutter --version | head -1
Flutter 1.11.0 • channel dev • https://github.com/flutter/flutter.git
$ screenshots
#############################################################
# 'flutter' must be in the PATH to use Screenshots
# You can usually add it to the PATH using# export PATH='$HOME/Library/flutter/bin:$PATH'
#############################################################
```
Maybe the error should be a bit clearer, like "Make sure you use $HOME instead of ~ in your path". Or in ``getExecutablePath()``, expand ``~`` to ``Platform.environment['HOME']``? Then again, not sure how many people have this issue.
