### ISSUE TITLE
Add retry mechanism for apk install?

### ISSUE THREAD

**Issue by Gerrel** [mmcc007/screenshots#140]
v2.0.2+1
The script was stuck on the line `Built build/app/outputs/apk/vat/debug/app-vat-debug.apk.`.
When closing the emulator manually the script continued (and failed).

Is it possible to add automated retry for installing the apk when it takes too long?

```
00:18 +2: create screenshot (tearDownAll)
teardown...
00:18 +2: All tests passed!
Stopping application instance.
Warning: framing is not enabled
Moving screenshots to android/fastlane/metadata/android/it-IT/images/phoneScreenshots
Running test_driver/main.dart on 'Nexus 6P' in locale it-IT with flavor vat ...
Starting application: test_driver/main.dart
Initializing gradle...                                              3,4s
Resolving dependencies...                                           3,0s
Installing build/app/outputs/apk/app.apk...                         3,9s
Running Gradle task 'assembleVatDebug'...                          27,0s
Built build/app/outputs/apk/vat/debug/app-vat-debug.apk.
Installing build/app/outputs/apk/app.apk...                      9970,2s (!)
Error: ADB exited with exit code 1
Performing Streamed Install
```

**Comment by mmcc007** [comment]
Is this reproducible without screenshots?

**Comment by Gerrel** [comment]
I have 28 localizations for the app. And this was the 12th in the list. Commenting out the rest and only using this localization does not reproduce this issue.

**Comment by mmcc007** [comment]
From what I can gather, it does not seem to be a screenshots-specific problem. Perhaps it is a resource issue?

In any case, it may be possible to add a timeout for long-running tests and retry a number of times. The timeout and retry can be defaulted to appropriate values and overridden by test.

Would this work?

**Comment by Gerrel** [comment]
Yes that would work.

**Comment by Gerrel** [comment]
Yes indeed when running screenshots for multiple localizations my system slowly runs out of disk space (below 3GB) and gives the error:
```
.../app/outputs/apk/app.apk: Failure [INSTALL_FAILED_INSUFFICIENT_STORAGE]
```
