### ISSUE TITLE
Support skipping fresh install

### ISSUE THREAD

**Issue by mcoolidge** [mmcc007/screenshots#142]
Flutter added a parameter: "flutter drive --no-build" to allow running on a preinstalled app and not re-building/installing. This would be useful for a number of reasons including working around native permission dialog blockers.

https://github.com/flutter/flutter/pull/30818

**Comment by mmcc007** [comment]
Ironically, the '--no-build' option was created as a result of an issue I opened (https://github.com/flutter/flutter/issues/28662) for another project. 😄

I usually like to describe the use case(s) adding a feature covers and how it should be used. In this case it seems that there is a clear performance advantage in using this feature if re-running screenshots locally (when not in CI). So adding an option to enable this feature from the command line would seem to be the way to go. For example,
```
screenshots --no-build
```

Would this work for you?

Can you elaborate on any other use cases if any (for example, native permission dialog blockers)?

**Comment by mcoolidge** [comment]
My immediate use case is to work around native iOS permission notifications. In this case, my plan is to install the app, use a command to accept the permissions, then run the screenshots tests.

We might also have backend web service changes that need to be tested against a previously installed app to make sure nothing broke. It would not be necessary to rebuild the app in this case.

**Comment by mmcc007** [comment]
Both use cases seem to be ones that are run locally (and not in a CI environment). So implementing by passing a parameter from the command line (as described above) seems like the way to go. 

Please confirm.

**Comment by mcoolidge** [comment]
These would mostly be run in a CI env but also manually as needed. The additional command line parameter would be perfect for us!! Thanks so much and it's funny how you wrote up the initial issue related to '--no-build'.

**Comment by mmcc007** [comment]
On reconsideration:
If passed on the command line, it would apply to all devices. For the more general use case where testing is being done on multiple devices, it might make sense to limit it to specific devices in the screenshots.yaml. (I am looking into splitting-off the core of screenshots into a more general testing platform for multiple attached devices, so this approach might be a better fit)

Would a config in screenshots.yaml still work for you?

**Comment by mcoolidge** [comment]
That would work as well!

**Comment by mmcc007** [comment]
Implemented!
Try it out with:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #142-no-build
pub global activate --source path .
```

For usage, see https://github.com/mmcc007/screenshots/blob/%23142-no-build/README.md#device-parameters.

Please let me know how it goes.

**Comment by mcoolidge** [comment]
Works perfectly! Very fast and works as expected

**Comment by mmcc007** [comment]
Great! Thanks for confirming.

I could also add it to the command line to globally over-ride any settings in screenshots.yaml.

Please let me know if you think this would also be useful or just over-kill for your use case, or in general.

**Comment by mcoolidge** [comment]
Actually, that would be useful as well so we don't need to modify our source for a specific version when doing regression testing. We consider our configs part of that "version" with the app itself.

**Comment by mmcc007** [comment]
Added support from command line.
Try it out with:
```
cd screenshots
git pull
```
See usage at 
https://github.com/mmcc007/screenshots/blob/%23142-no-build/README.md#usage

Please let me know how it goes.

**Comment by mcoolidge** [comment]
It works, but I wasn't immediately sure how to use the command. Does --[no-]build mean it could be --no-build or --build? What if you do --no-build false? Is that the same as --build true? This is due to the wording of the flutter command, but users will likely have to try each command to make sure. This might be just tweaking the docs slightly.

Maybe (and this is a different item completely) it would be helpful for screenshots to print the options it's using.

Thank you so much!! Fantastic tool!!

**Comment by mmcc007** [comment]
I know what you mean. Changed invocation from command line to make it consistent with how it is used in config file. Added no build messaging.

Try it out with:
```
cd screenshots
git pull
```
See usage at 
https://github.com/mmcc007/screenshots/blob/%23142-no-build/README.md#usage

Please let me know how it goes.

**Comment by mcoolidge** [comment]
Looks good!

**Comment by mmcc007** [comment]
Great!. If there is nothing else will merge and close. 

Thanks for your feedback, confirmations and affirmations.

If you like sylph, you oughta put a star🌟 on it! 😂
