### ISSUE TITLE
The input file is invalid

### ISSUE THREAD

**Issue by Ahmadre** [mmcc007/screenshots#148]
I cloned the screenshots repo and switched into example path. 
I wanted to run it with ```screenshots```,  but following error is coming up:

```bash
    The input file is invalid.
    screenshots my-input-file.txt
    screenshots my-input-file.txt my/output/folder
```

Could somone please fix that? I installed screenshots like always over pub.dev. Everything is fine on my mac, but it won't work on the example and also on my own project.

Thx :)

**Comment by Ahmadre** [comment]
Sorry forgot my details:
```bash
   + screenshots: 2.1.0+1
   Flutter 1.10.15-pre.351 • channel master • https://github.com/flutter/flutter.git
   Framework • revision 8e0799a657 (7 days ago) • 2019-10-30 23:33:38 -0700
   Engine • revision b16eab6aff
   Tools • Dart 2.6.0 (build 2.6.0-dev.8.2 d50c158d42)
```

**Comment by mmcc007** [comment]
Try running:
```
cd example
screenshots -c screenshots_ios.yaml -v
```
You should get output similar to:
https://travis-ci.com/mmcc007/screenshots/jobs/249814133#L817

If not, switch to the stable channel
```
flutter channel stable
```
and try again.

If still not working, please send the output.

**Comment by Ahmadre** [comment]
Nope, not working. Same output:
<img width="664" alt="Bildschirmfoto 2019-11-08 um 11 35 00" src="https://user-images.githubusercontent.com/18512224/68470236-f0782680-021b-11ea-845f-50b5856c3db3.png">

**Comment by mmcc007** [comment]
It looks like you have more than one executable called `screenshots` in your PATH. Try using `which screenshots` to tell which one you are using. You should be getting something like:
```
which screenshots
/Users/rebar/.pub-cache/bin/screenshots
```
If not, you may need to change your PATH env var to fix it.

To run without changing PATH try
```
/Users/rebar/.pub-cache/bin/screenshots
```

**Comment by Ahmadre** [comment]
Solved! That was my issue! I don't know why but it installed my pub packages on /usr/local/bin 😫 

Thank you sooo much!!! You saved my day 😃
