### ISSUE TITLE
LandscapeLeft / LandscapeRight not working

### ISSUE THREAD

**Issue by Ahmadre** [mmcc007/screenshots#150]
At first: thank you soo much for all of your work 👍 

Landscape Mode is not working:
![Nexus 9-1](https://user-images.githubusercontent.com/18512224/68514443-0b7b8280-027e-11ea-9ef3-2f613b6bd4c4.png)

(Nexus 9 - LandscapeLeft)

**Comment by mmcc007** [comment]
The art for landscape status bars (and navigation bars for android) are not currently available (see [README](https://github.com/mmcc007/screenshots/blob/master/test/resources/README.md) to create). So framing is currently supposed to be disabled when device in config is not in portrait.

Framing is now disabled when not running in portrait

Install fix with:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #150_orientation
pub global activate --source path .
```
and test.

Let me know how it goes.

**Comment by Ahmadre** [comment]
Oh yeah I read that earlier here somewhere in the comments. Thought it was related to some other cases. 

All right it works now. Landscape is now as raw screenshots.

Thanks 🙏
