### ISSUE TITLE
Defining multiple tests always takes first

### ISSUE THREAD

**Issue by Gerrel** [mmcc007/screenshots#152]
In screenshots.yaml (^2.1.0+1) I have:

```
tests:
# Note: flutter driver expects a pair of files eg, main1.dart and main1_test.dart
  - test_driver/main_dark.dart
  - test_driver/main.dart
```

For creating screenshots in light and dark mode.

When running the first test (main_dark.dart) it executes:
`Running test_driver/main_dark.dart on 'Nexus 6P' in locale nl-NL with flavor currency...
[        ] executing: [./] flutter -d emulator-5554 drive --flavor currency test_driver/main_dark.dart`

And that's good, but when running the second it executes:
`Running test_driver/main.dart on 'Nexus 6P' in locale nl-NL with flavor currency...
[        ] executing: [./] flutter -d emulator-5554 drive --flavor currency test_driver/main_dark.dart --flavor currency test_driver/main.dart`

It appends both and flutter takes the first one.

**Comment by mmcc007** [comment]
Thanks!

**Comment by mmcc007** [comment]
Upgrade with
```
pub global activate screenshots
```
