### ISSUE TITLE
would be nice to include example of using as a package

### ISSUE THREAD

**Issue by Xgamefactory** [mmcc007/screenshots#157]
guess example is wrong
could you add example about how to use screenshot package runtime not from command line.

**Comment by mmcc007** [comment]
screenshots is intended to be used as a command line utility. Can you elaborate on your use case?

**Comment by Xgamefactory** [comment]
thanks for reply it is possible to get screenshot internally with native code
it would be nice to add such feature with device framing support as a package not just cli.

**Comment by mmcc007** [comment]
screenshots is already available as a package. Can you explain what problem you are trying to solve?

**Comment by Xgamefactory** [comment]
an example how to use this plugin as a runtime package not cli

**Comment by mmcc007** [comment]
Include it in any dart program by importing the package `import 'package:screenshots/screenshots.dart';`.

**Comment by Xgamefactory** [comment]
we did importing the package url. which method to call for capturing screen ?
there is no example how to use as a package ? as a standalone runtime package
like ...capture(widget etc.

**Comment by Xgamefactory** [comment]
runtime screenshot taking for ios code is

https://github.com/innovationmauritiustelecom/screenshotshareimage_plugin_flutter/blob/master/ios/Classes/ScreenshotShareImagePlugin.m
```
CGFloat scale = [UIScreen mainScreen].scale;
    
    UIGraphicsBeginImageContextWithOptions(view.bounds.size, view.opaque, 0.0f);
    
    [view drawViewHierarchyInRect:view.bounds afterScreenUpdates:YES];
    UIImage *img = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
```

**Comment by mmcc007** [comment]
screenshots is probably not suitable for creating screenshots from a plugin. It takes screenshots from a test using flutter driver.
