### ISSUE TITLE
NoSuchMethodError: The method 'map' was called on null.

### ISSUE THREAD

**Issue by Xgamefactory** [mmcc007/screenshots#158]
flutter doctor -v
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.14.6 18G103, locale en-TR)
    • Flutter version 1.9.1+hotfix.6 at /Users/fersmart/SDK_all/flutter
    • Framework revision 68587a0916 (10 weeks ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

Have attached iphone XS Max

```
 screenshots
Starting flutter daemon...                                          0.6s
Unhandled exception:
NoSuchMethodError: The method 'map' was called on null.
Receiver: null
Tried calling: map<String>(Closure: (dynamic) => String)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      Config._processList (package:screenshots/src/config.dart:128:17)
#2      Config.tests (package:screenshots/src/config.dart:53:29)
#3      isValidConfig (package:screenshots/src/validate.dart:19:30)
<asynchronous suspension>
#4      Screenshots.run (package:screenshots/src/run.dart:109:16)
<asynchronous suspension>
#5      screenshots.<anonymous closure> (package:screenshots/src/run.dart:48:26)
<asynchronous suspension>
#6      AppContext.run.<anonymous closure> (package:tool_base/src/base/context.dart:153:29)
<asynchronous suspension>
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1463:12)
#11     AppContext.run (package:tool_base/src/base/context.dart:152:18)
<asynchronous suspension>
#12     runInContext (package:screenshots/src/context_runner.dart:16:24)
<asynchronous suspension>
#13     screenshots (package:screenshots/src/run.dart:47:12)
<asynchronous suspension>
#14     main (file:///Users/fersmart/.pub-cache/hosted/pub.dartlang.org/screenshots-2.1.1/bin/main.dart:122:25)
<asynchronous suspension>
#15     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:303:32)
#16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

**Comment by mmcc007** [comment]
Sorry about the obscure message.
Check that `tests` in screenshots.yaml is configured as expected. 
Let me know if this helps.

**Comment by Xgamefactory** [comment]
is this plugin just for working with test ? anyway to make screenshot on actual project not test ?

**Comment by mmcc007** [comment]
were you able to resolve this issue?

**Comment by Xgamefactory** [comment]
after adding test driver getting another error #160

**Comment by mmcc007** [comment]
Looks like this issue is resolved?

**Comment by Xgamefactory** [comment]
yes but this is connected with other issue https://github.com/mmcc007/screenshots/issues/160

**Comment by avioli** [comment]
I know this issue is closed, but this was happening to me because the documentation failed to tell me that the file `screenshots.yaml` **has** to have, at minimum, the following keys: `tests`, `staging`, `locales`, `devices.ios` or `devices.android`, and finally `frame`.

I thought I can even go with just:

```
devices:
  ios:
    iPhone SE:
```

**Comment by mmcc007** [comment]
@avioli That can be added to the validation step, if you want to create an issue.
