### ISSUE TITLE
Expected a key while parsing a block mapping

### ISSUE THREAD

**Issue by natanloterio** [mmcc007/screenshots#170]
Hi @mmcc007 , I just ran the example screenshots.yaml from your repo and got this issue:
https://gist.github.com/natanloterio/e2041ae8bbb56a058ea34df00ae763c8

This is the file I'm using:
https://gist.github.com/natanloterio/ab9ea38745f34d31eed8973120fbf296

The yaml file syntax seems to be wrong, but I couldn't find how to fix it. 
Can you give me a help on this one?

**Comment by mmcc007** [comment]
Try uncommenting
```
#   devices:
```
to
```
devices:
```
(no spaces)

**Comment by natanloterio** [comment]
Got another error after changing what you said. 
https://gist.github.com/natanloterio/17816438dbdfe56d2e12f0bbb9b1cd85

This is the file now:
https://gist.github.com/natanloterio/d4189cbbe2229d93cb6ac1aa42e1cce7

**Comment by natanloterio** [comment]
Just find out the problem. Looks like a 'space' was missing at  `- test_driver/main.dart` 
![image](https://user-images.githubusercontent.com/2896563/70737106-8d812000-1cf0-11ea-9b46-cda4f2cf75cc.png)
https://www.diffchecker.com/utfNO2uL

**Comment by mmcc007** [comment]
So this issue is resolved?

**Comment by natanloterio** [comment]
Yes, it was! 
Thank you for your help
