### ISSUE TITLE
iOS 13.X "No Device connected" when running Appium from Itellij IDEA.

### ISSUE THREAD

**Issue by chuklov** [mmcc007/screenshots#190]
I'm having an issue with running automation scripts over Appium server and Intellij IDEA. I have no issue with running these tests on iOS 12.X and 11.X, however, on 13.x it says "No Device Connected"

Starting Appium desktop and Start Inspection session find the device and working fine. Also all webdrivers from xcode also installed and no issues. The only issue is to find a device from Intellij IDEA. 

/Library/Java/JavaVirtualMachines/jdk1.8.0_241.jdk/Contents/Home/bin/java -ea -
log4j: reset attribute= "false".
log4j: Threshold ="null".
log4j: Level value for root is  [info].
log4j: root level set to INFO
log4j: Class name: [com.epam.ta.reportportal.log4j.appender.ReportPortalAppender]
log4j: Parsing layout of class: "org.apache.log4j.PatternLayout"
log4j: Setting property [conversionPattern] to [[%d{HH:mm:ss}] %-5p (%F:%L) - %m%n].
log4j: Adding appender named [ReportPortalAppender] to category [root].

Apr 01, 2020 6:12:45 PM com.appium.schema.CapabilitySchemaValidator validateRemoteHosts
INFO: ATD is Running on 127.0.0.1
                                 _   _          _ 
  _ __     __ _   _ __    __ _  | | | |   ___  | |
 | '_ \   / _` | | '__|  / _` | | | | |  / _ \ | |
 | |_) | | (_| | | |    | (_| | | | | | |  __/ | |
 | .__/   \__,_| |_|     \__,_| |_| |_|  \___| |_|
 |_|                                              
PARALLEL
  _   _             ____                   _                          ____                                         _                _ 
 | \ | |   ___     |  _ \    ___  __   __ (_)   ___    ___   ___     / ___|   ___    _ __    _ __     ___    ___  | |_    ___    __| |
 |  \| |  / _ \    | | | |  / _ \ \ \ / / | |  / __|  / _ \ / __|   | |      / _ \  | '_ \  | '_ \   / _ \  / __| | __|  / _ \  / _` |
 | |\  | | (_) |   | |_| | |  __/  \ V /  | | | (__  |  __/ \__ \   | |___  | (_) | | | | | | | | | |  __/ | (__  | |_  |  __/ | (_| |
 |_| \_|  \___/    |____/   \___|   \_/   |_|  \___|  \___| |___/    \____|  \___/  |_| |_| |_| |_|  \___|  \___|  \__|  \___|  \__,_|
                                                                                                                                      
No Device Connected

Process finished with exit code 0

I'm using this project to make automation tests: https://github.com/AppiumTestDistribution/PageObjectPatternAppium

@saikrishna321. maybe you have ideas or let me know if you need more details. 

Thanks

**Comment by mmcc007** [comment]
Looks like this was posted to wrong project
