### ISSUE TITLE
Localization not working

### ISSUE THREAD

**Issue by ykorzikowski** [mmcc007/screenshots#20]
Relates to https://github.com/flutter/flutter/issues/27785
Bump this for fixing. 

I noticed that on some runs the localizations worked for me with ios simulator. Tested it with de_DE and en_GB. 

German screenshots were located in the gb dir, the english ones in the german dir. Not reproducible. 

Is there any way to workaround this issue? E.g. restart emulator with proper locale to override flutter driver.

**Comment by mmcc007** [comment]
Interesting on ios simulator result... haven't seen the issue with switching delivery of images by locales issue before, but will keep an eye out for it.

Might be worth adding some more jobs to the Travis run in dev (or try on local machine) and see if there is a workaround for the flutter issue. 

Changing the locale of either the emu or the host machine before each Screenshots run and then running Screenshots for each locale separately, might have some potential. This would probably require adding an option to not clear the image destination dirs on each run of Screenshots.

(BTW: it helps if you also add a thumbs-up to the first issue flutter/flutter#27785 (comment) -- every thumbs-up helps!)

**Comment by ykorzikowski** [comment]
> Changing the locale of either the emu or the host machine before each Screenshots run and then running Screenshots for each locale separately, might have some potential. This would probably require adding an option to not clear the image destination dirs on each run of Screenshots.

I did only a quick review on the code. Can you tell how difficult it is to add an option for this?

**Comment by mmcc007** [comment]
Should be straight-forward enough. Can be a command-line argument, or added to the screenshots.yaml. Which ever is most convenient to user for automation. 

Since it may take a while for flutter team to get to fix (based on how it is currently prioritized), and there may be some more uses for it in future -- not clear, it should probably go in the screenshots.yaml

**Comment by mmcc007** [comment]
I'm looking into starting an emulator faster (and behave better) on Travis for some other projects. I hope to be able to use the result here so we can do some more experimentation to find a workaround for the flutter issue with localization.

In the meantime, if you want to implement the 'disable-clear-directory' feature, please feel free to create a PR.

**Comment by mmcc007** [comment]
An (temporary) alternative to adding the disable-clear-directory feature is to write a script that copies the images elsewhere between each run and then copies them all back at the end of all the runs.

**Comment by mmcc007** [comment]
Added a fix for localization. Try it out with:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #19_#20_localization
pub global activate --source path .
cd example
screenshots
```
Give it a shot and let me know how it goes. A confirmation of fix would help get fix into a release.
