### ISSUE TITLE
Screenshots not moved into the correct directory

### ISSUE THREAD

**Issue by BouweCeunen** [mmcc007/screenshots#208]
While running screenshots for Android, it places all the screenshots in the phoneScreenshots directory and none in the other. 
![image](https://user-images.githubusercontent.com/5576686/87551422-a13e9b80-c6b0-11ea-85cb-770bb7a135fa.png)

Fastlane wants them into the correct folders https://docs.fastlane.tools/actions/supply/#images-and-screenshots.

Is this as designed or did I configure something wrong?

**Comment by mmcc007** [comment]
It seems Supply expects screenshots by screen size, not model of phone. Hope that helps.

**Comment by BouweCeunen** [comment]
Not sure if I understand correctly. Fastlane will put the images that are in `phoneScreenshots` in the Phone tab of Google Play Developer Console. There's also a Tablet tab for 7 inch and 10 inch, fastlane will upload the images in `sevenInchScreenshots` to the 7 inch tab and the images in `tenInchScreenshots` to the 10 inch tab. How it is now it will not do that correctly because there are no images in the other two folders.

I now execute these lines after running `screenshots` to put them all in the right folders.

```
mv ./android/fastlane/metadata/android/en-US/images/phoneScreenshots/*Nexus*7*.png ./android/fastlane/metadata/android/en-US/images/sevenInchScreenshots/
mv ./android/fastlane/metadata/android/en-US/images/phoneScreenshots/*Nexus*10*.png ./android/fastlane/metadata/android/en-US/images/tenInchScreenshots/
```

**Comment by mmcc007** [comment]
On looking at [screens.yam](https://github.com/mmcc007/screenshots/blob/d542991cf0d6fa10897746695f0aa4ed8bb973b4/lib/resources/screens.yaml)l, the screens for the phone models you are using are not currently supported. So they are placed in the default directory as part of default behavior. Thanks for pointing out how you work around it.

If you use Nexus 7 and Nexus 10 a lot, you might want to open an issue to request support for these models and their screen sizes.

**Comment by BouweCeunen** [comment]
It's not a big issue for me right now. Thanks for clarifying!
