### ISSUE TITLE
When a test fails, simulator still running

### ISSUE THREAD

**Issue by dalewking** [mmcc007/screenshots#36]
Anyway to get screenshots to clean up after itself if an error occurs in the testing. (e.g. a widget not found or too many widgets found)?

The workaround now (for IOS) is to open the simulator and then quit it.

**Comment by mmcc007** [comment]
It may be possible, but I don't see it as a use case that screenshots tries to cover.... 

The recommended way to make sure each of your tests run correctly before running screenshots is to run each test standalone like:
```
flutter driver test_driver/main1.dart
flutter driver test_driver/main2.dart
etc...
```
Does this get you closer to where you're trying to get?
