### ISSUE TITLE
iPhone X status bar white on light gray

### ISSUE THREAD

**Issue by dalewking** [mmcc007/screenshots#37]
The status bar in my iPhone X screenshots are generated with white on light gray so look peculiar.

<img width="282" alt="Screen Shot 2019-04-24 at 12 45 05 AM" src="https://user-images.githubusercontent.com/346062/56633092-c61d9d80-662a-11e9-8ade-1d4014b0305a.png">

In the actual simulator I have black text over light gray.

Perhaps you have some dark mode enabled for your simulator, but it seems to me the library should look at what color the status bar is in the captured screen shot and decide whether it should overlay black or white on top of it.

**Comment by mmcc007** [comment]
The images returned from the flutter graphics engine from a screenshots call does not include the status bar. So I made a simplifying assumption about what color to use for the status bar (it was either black or white and I picked white). There is probably some threshold policy that iOS uses to select the color. This threshold policy may be available somewhere or can be implemented using a suitably selected threshold based on something like the brightness of the screenshot image.

What do you think? Would a threshold based on brightness around the 'status bar area' be ok?

**Comment by dalewking** [comment]
That is what I was suggesting.

After further research the copper of the status bar is generally controlled by the color of the AppBar, but this screen didn't have an app bar. I will probably do one of the techniques to change the color for this screen.

**Comment by mmcc007** [comment]
The app bar (for iPhone X and beyond) hasn't been implemented yet.

If the app bar color policy (which results in either black or white) is driving the color of the status bar, then it may be a good time to implement the app bar.

In any case, there is probably a call to imagemagik that can get the 'brightness' that can be used to select black or white.

**Comment by mmcc007** [comment]
I added a feature for selecting a black or white status bar based on a 'brightness' threshold.

You can find it in the dev branch. To install it use:
```
pub global activate --source path .
```

I  added black and white status bars for iPhone X (and beyond). So it should now be selecting the correct status bar color as described in this issue.

Let me know if the new feature resolves this issue.
