### ISSUE TITLE
Is there a way of knowing which locale/device that is being tested at the driver test code?

### ISSUE THREAD

**Issue by supergarotinho** [mmcc007/screenshots#39]

**Comment by supergarotinho** [comment]
Knowing the locale:
- I can test if the texts have been set to the right locale.

Knowing if the device is IOS or Android is useful if:
- I have different things happening for each type, ex: different bio auth method

Knowing the device screen, i can see if the responsive strategy were properly developed.

**Comment by mmcc007** [comment]
Flutter has methods for indicating which locale and device type and screen type your app is running on. 

Let me know if this answers your question

**Comment by supergarotinho** [comment]
I didn't found any information on how to get this values from the app/vm at the driver/host/test side. Do you know a way?

**Comment by mmcc007** [comment]
From a quick review of what I know (and just searched):
- Locale
https://master-docs-flutter-io.firebaseapp.com/flutter/widgets/Localizations-class.html
https://pub.dartlang.org/packages/devicelocale
https://medium.com/saugo360/managing-locale-in-flutter-7693a9d4d6ac
- Device
https://pub.dartlang.org/packages/device_info
- Screen
https://docs.flutter.io/flutter/widgets/MediaQuery-class.html

Off the top of my head, I don't know how much of this info is available during an integration test.

**Comment by supergarotinho** [comment]
Thank you mmcc007, but i think that i was not very clear. This things are relatively simple and easy because you are doing it within the app. In the middle of the integration tests that are being called by the driver, i didn't saw a way to know this things. Since screenshots executes the same tests at several devices and locales, o good thing is to let the actual locale and device to be known by the test.

For me, this is essencial. Simple things like finding and tapping at the material pageback button depends on the locale that is being used within the app. In my case, if is en, the pageback button can be found by: `find.byTooltip("Back")`. If the test is now testing with a portuguese locale, the tooltip is now "Voltar".

Also, depending on the size of the screen, i will hide, show or replace some widgets on the screen. I want to test this behavior also.

At the test case, in the integration test method, i didn't found a way to know the device type or the locale that is being tested now. But, screenshots probably know it!

**Comment by mmcc007** [comment]
Ah, I see! Interesting use case.

This is something that is probably more appropriate for 'flutter driver' to know, if it doesn't already know (to avoid creating a dependency on screenshots for those that are not using screenshots). I don't think it currently gets this info from the device, but it probably should. So it might be worth creating an issue about this in https://github.com/flutter/flutter/issues.

Screenshots knows some of this info (there may be exceptions). It may be possible to make what screenshots knows available to the test using something like a Map.

Screenshots knows:
- current screen size (eg, 5.5inch)
- current locale (eg, en-US)
- current device name (eg, Nexus 6P)
- current device type (eg, ios)

Is this enough?

**Comment by supergarotinho** [comment]
Thank you. I agree that is something that should be implemented at the flutter driver. So the tests wont depend on the screenshots packages. I opened an issue about that. Also, i looked over all flutter driver issues and mapped the related ones.

https://github.com/flutter/flutter/issues/31609

I think we should close this one. Thank you!

**Comment by mmcc007** [comment]
Good job on submitting a new flutter issue.

In my experience it can take some time before these flutter issues are resolved (currently 5000+ open issues... and ~15000 closed issues over several years)

What do you think about implementing the Map described above in screenshots until this issue is resolved? Is it worth it?

**Comment by supergarotinho** [comment]
If, it wont take too much effort to implement this feature on screenshots now, i totally agree.

Well, the first 2 issues in the report that you sent are related to our issue.

The first one is totally related. The second is somewhat related: when this second issue has been done, the need of having the locale information at the driver is 100%. Because we need this info to do some things like: open the drawer; tap on the page back button. And, creating the screenshot for each locale is super important. I think that is one of the most relevant features of the screenshot component.

**Comment by mmcc007** [comment]
I don't think it is particularly difficult to implement in screenshots.

BTW: apparently there is a way to implement custom flutter driver commands:
https://github.com/flutter/flutter/issues/3191
It does not seem particularly clear how to implement a custom command, but might be worth looking into for your use case.

**Comment by mmcc007** [comment]
I added passing of a Map to tests.
You can install it from the dev branch using:
```
pub global activate --source path .
```

And use the map in your tests using something like:
```
await config.retrieveEnv();
final screenshotsEnv = config.screenshotsEnv;
```

Let me know how this works out.
