### ISSUE TITLE
Running tests on azure pipelines

### ISSUE THREAD

**Issue by gedw99** [mmcc007/screenshots#44]
Azure has all desktop OS's with identical script driving them.
It natively runs in UI mode, so screenshots and Integration Test work.

It's much faster than Travis 
It's free for open Github and Bitbucket.

 If anyone interested as I will be using this.
Maybe this should be part of the Fledge project instead ?

**Comment by mmcc007** [comment]
Does Azure have support for macOS? If so, it should be able to run both Fledge and Screenshots.

Let me know if you get anywhere. I'd be interested in giving it a shot.
