### ISSUE TITLE
command failed: cmd='adb emu kill'

### ISSUE THREAD

**Issue by Alecsplus** [mmcc007/screenshots#45]
On my Linux PC, nexus 6 screenshot for 1 language is OK.

When I try to use another localization, when I starts the screenshots command I receive this error:
`command failed: cmd='adb emu kill'`
after the first language ends its work.

Here the full log:

`alessandroid@TUXEDO:~/Developer/PFP/testFlutter/flutter_app$ /home/alessandroid/.pub-cache/bin/screenshots 
Warning: 'Nexus 6P' does not have a matching emulator.
       : Using 'Nexus_6P_API_Q'.
Warning: Flutter integration tests do not work in multiple locals.
  See comment on issue:
  https://github.com/flutter/flutter/issues/27785#issue-408955077
  for details.
  and provide a thumbs-up on the comment to prioritize a fix for this issue!

  In the meantime, while waiting for a fix, only use the default locale
  in screenshots.yaml

Clearing images in android/fastlane/metadata/android/it-IT/images/phoneScreenshots for 'Nexus 6P'...
Clearing images in android/fastlane/metadata/android/es-ES/images/phoneScreenshots for 'Nexus 6P'...
Clearing images in android/fastlane/metadata/android/en-US/images/phoneScreenshots for 'Nexus 6P'...
Starting emulator 'Nexus 6P' in locale it-IT ...
Emulator is ready
Capturing screenshots with test app test_driver/app.dart on emulator 'Nexus 6P' in locale it-IT ...
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Initializing gradle...                                              2,1s
Resolving dependencies...                                           4,1s
Installing build/app/outputs/apk/app.apk...                         5,8s
Running Gradle task 'assembleDebug'...                             10,1s
Built build/app/outputs/apk/debug/app-debug.apk.
Installing build/app/outputs/apk/app.apk...                         2,0s
I/flutter ( 9623): Observatory listening on http://127.0.0.1:33407/cu3jrGHxfII=/
00:00 +0: Counter App (setUpAll)
00:02 +0: Counter App starts at 0
Screenshot myscreenshot1 created
00:04 +1: Counter App increments the counter
Screenshot myscreenshot2 created
00:07 +2: Counter App (tearDownAll)
00:07 +2: All tests passed!
Stopping application instance.
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:35367/cu3jrGHxfII=/
[trace] FlutterDriver: Isolate found with number: 540638223
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
Processing screenshots from test...
Moving screenshots to android/fastlane/metadata/android/it-IT/images/phoneScreenshots
Stopping emulator: 'Nexus 6P' ...
Emulator is stopped
Starting emulator 'Nexus 6P' in locale es-ES ...
Emulator is ready
Capturing screenshots with test app test_driver/app.dart on emulator 'Nexus 6P' in locale es-ES ...
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Initializing gradle...                                              2,1s
Resolving dependencies...                                           4,6s
Installing build/app/outputs/apk/app.apk...                         7,9s
Running Gradle task 'assembleDebug'...                              2,3s
Built build/app/outputs/apk/debug/app-debug.apk.
I/flutter (12254): Observatory listening on http://127.0.0.1:44971/fDX1UM8YUb0=/
00:00 +0: Counter App (setUpAll)
00:02 +0: Counter App starts at 0
Screenshot myscreenshot1 created
00:04 +1: Counter App increments the counter
Screenshot myscreenshot2 created
00:07 +2: Counter App (tearDownAll)
00:07 +2: All tests passed!
Stopping application instance.
[info ] FlutterDriver: Connecting to Flutter application at http://127.0.0.1:38161/fDX1UM8YUb0=/
[trace] FlutterDriver: Isolate found with number: 1027751757
[trace] FlutterDriver: Isolate is paused at start.
[trace] FlutterDriver: Attempting to resume isolate
[trace] FlutterDriver: Waiting for service extension
[info ] FlutterDriver: Connected to Flutter application.
Processing screenshots from test...
Moving screenshots to android/fastlane/metadata/android/es-ES/images/phoneScreenshots
Stopping emulator: 'Nexus 6P' ...
adb server version (41) doesn't match this client (39); killing...
ADB server didn't ACK
Full server startup log: /tmp/adb.1000.log
Server had pid: 21431
--- adb starting (pid 21431) ---
adb I 05-18 18:24:13 21431 21431 main.cpp:57] Android Debug Bridge version 1.0.39
adb I 05-18 18:24:13 21431 21431 main.cpp:57] Version 1:8.1.0+r23-5~18.04
adb I 05-18 18:24:13 21431 21431 main.cpp:57] Installed as /usr/lib/android-sdk/platform-tools/adb
adb I 05-18 18:24:13 21431 21431 main.cpp:57] 
adb I 05-18 18:24:13 21431 21431 adb_auth_host.cpp:416] adb_auth_init...
adb I 05-18 18:24:13 21431 21431 adb_auth_host.cpp:174] read_key_file '/home/alessandroid/.android/adbkey'...
adb I 05-18 18:24:13 21431 21431 adb_auth_host.cpp:391] adb_auth_inotify_init...
adb server killed by remote request
--- adb starting (pid 21438) ---
adb I 05-18 18:24:13 21438 21438 main.cpp:60] Android Debug Bridge version 1.0.41
adb I 05-18 18:24:13 21438 21438 main.cpp:60] Version 28.0.3-5475833
adb I 05-18 18:24:13 21438 21438 main.cpp:60] Installed as /home/alessandroid/Android/Sdk/platform-tools/adb
adb I 05-18 18:24:13 21438 21438 main.cpp:60] 
adb I 05-18 18:24:13 21438 21438 auth.cpp:405] adb_auth_init...
adb I 05-18 18:24:13 21438 21438 auth.cpp:380] adb_auth_inotify_init...
adb I 05-18 18:24:13 21438 21445 transport.cpp:281] emulator-5554: read thread spawning
adb I 05-18 18:24:13 21438 21446 transport.cpp:294] emulator-5554: write thread spawning
adb I 05-18 18:24:13 21438 21438 adb.cpp:110] emulator-5554: already offline

* failed to start daemon
error: no emulator connected: cannot connect to daemon
Unhandled exception:
command failed: cmd='adb emu kill'
#0      cmd (package:screenshots/utils.dart:38:5)
#1      emulator (package:screenshots/screenshots.dart:169:5)
<asynchronous suspension>
#2      run (package:screenshots/screenshots.dart:58:15)
<asynchronous suspension>
#3      main (file:///home/alessandroid/.pub-cache/hosted/pub.dartlang.org/screenshots-0.1.7/bin/main.dart:93:9)
<asynchronous suspension>
#4      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:298:32)
#5      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:171:12)
`

**Comment by mmcc007** [comment]
It looks like you are running into 2 problems, one related to adb version number, the other, and more significantly, related to a flutter driver bug when running internatationalisation. 

The flutter driver bug prevents you from generating screenshots in any non-default locale. The workaround for the moment is to run screenshots in just the default locale (by removing multiple locales in screenshots.yaml).

Try running screenshots in just the default locale and let me know what happens.

For anyone reading this, please give a 👍 to the issue at:
https://github.com/flutter/flutter/issues/27785#issue-408955077
(give 👍 to the first comment to get visibility in flutter issue reports)

**Comment by Alecsplus** [comment]
Dear mmcc007, thank you for your reply.
Solving the adb error version problem, now I am able to run correctly the screenshots. The "only" problem (surely due to the flutter driver bug) il that all the screens are in the main language and are not localized...

:(

**Comment by mmcc007** [comment]
Glad you were able to make progress with the adb version number. 

Until such time as the flutter driver bug is resolved (or a workaround is found), unfortunately, it will not be possible to make localized screenshots.

Thank you for your feedback. Let me know if you run into any other problems.

**Comment by Alecsplus** [comment]
Thanks to you for your job, for the moment I will manually change the language on the device...

Bye.
