### ISSUE TITLE
Flavor support

### ISSUE THREAD

**Issue by robinbonnes** [mmcc007/screenshots#55]
First of all, thanks for this great tool!

Can we add flavor support? For example:
```screenshots --flavor [flavorname]```

**Comment by mmcc007** [comment]
Glad you like it!

Can you explain more about what you have in mind. I haven't used flavors much, but seems like each flavored app should have an integration test (probably with a lot shared between apps). If so, it should be possible to call each flavored integration test as normal. If not, please let me know how flavored integration tests are called.

**Comment by Alecsplus** [comment]
In my case, I have 2 flavours (A or B) in Android, and 2 different entry point in flutter (mainA.dart, mainB.dart). 

Here the error I receive when I run screenshot command:

Warning: 'Nexus 6P' does not have a matching emulator.
       : Using 'Nexus_6P_API_28'.
Clearing images in android/fastlane/metadata/android/es-ES/images/phoneScreenshots for 'Nexus 6P'...
Starting emulator 'Nexus 6P' in locale es-ES ...
Emulator is ready
Capturing screenshots with test app test_driver/app.dart on emulator 'Nexus 6P' in locale es-ES ...
Using device Android SDK built for x86.
Starting application: test_driver/app.dart
Initializing gradle...                                              0,4s
Resolving dependencies...                                           1,6s
Installing build/app/outputs/apk/app.apk...                         0,9s

The Gradle project does not define a task suitable for the requested build.
The android/app/build.gradle file defines product flavors: A, B
You must specify a --flavor option to select one of them.
Gradle build aborted.
Unhandled exception:
command failed: cmd='flutter drive test_driver/app.dart'
#0      streamCmd (package:screenshots/utils.dart:67:7)
<asynchronous suspension>
#1      screenshots (package:screenshots/screenshots.dart:112:9)
<asynchronous suspension>
#2      run (package:screenshots/screenshots.dart:59:17)
#3      _RootZone.runUnary (dart:async/zone.dart:1379:54)
#4      _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#6      Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#7      Future._complete (dart:async/future_impl.dart:473:7)
#8      _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#11     emulator (package:screenshots/screenshots.dart)
#12     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#13     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#14     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#15     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#16     Future._complete (dart:async/future_impl.dart:473:7)
#17     _SyncCompleter.complete (dart:async/future_impl.dart:51:12)
#18     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:28:18)
#19     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:294:13)
#20     streamCmd (package:screenshots/utils.dart)
#21     _RootZone.runUnary (dart:async/zone.dart:1379:54)
#22     _FutureListener.handleValue (dart:async/future_impl.dart:126:18)
#23     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:639:45)
#24     Future._propagateToListeners (dart:async/future_impl.dart:668:32)
#25     Future._completeWithValue (dart:async/future_impl.dart:483:5)
#26     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:513:7)
#27     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#28     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#29     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#30     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)

How we can solve?

**Comment by mmcc007** [comment]
I added support for flavors. Try it out on your app with:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #55_flavor_support
pub global activate --source path .
cd <your project>
screenshots -f <your flavor>
```
... and let me know.
