### ISSUE TITLE
"Screenshots expects no devices to be running at startup"

### ISSUE THREAD

**Issue by robinbonnes** [mmcc007/screenshots#56]
I get this error, because `isAnyDeviceRunning()` in the utils.dart file checks if the command `flutter devices` contains the string "`No devices detected.`". However, in the latest flutter version it detects `macOS` and `web` also as device.

**Comment by mmcc007** [comment]
Can you provide the output of `flutter devices` on you machine and your `flutter doctor -v`.

**Comment by mmcc007** [comment]
I tried on Flutter Channel master, v1.7.4-pre.32 (8 days ago) and it gave anticipated results.
```
$ flutter devices
No devices detected.

Run 'flutter emulators' to list and start any available device emulators.

Or, if you expected your device to be detected, please run "flutter doctor" to diagnose potential issues, or visit https://flutter.dev/setup/ for troubleshooting tips.
```

If you can provide your version of flutter and your output I can look into it.

**Comment by zanuka** [comment]
@robinbonnes I run into this all the time using screenshots package. Even when you completely quit the Apple Simulator app, it will still happen. so as part of my workflow now I just have a zsh alias for this command: `sudo killall -9 com.apple.CoreSimulator.CoreSimulatorService` 

Then I'm able to run `screenshots` ... it's definitely not ideal and would be great to find a more permanent fix.

**Comment by mmcc007** [comment]
@zanuka can you send me the output of `flutter devices`. There might be another way to handle devices.

**Comment by matthew-carroll** [comment]
I'm also running into this issue. Here is the output from `flutter devices`:

```
2 connected devices:

macOS  • macOS  • darwin-x64     • Mac OS X 10.14.3 18D109
Chrome • chrome • web-javascript • Google Chrome 75.0.3770.100 
```

**Comment by mmcc007** [comment]
Removed requirement that no emulators/simulators or devices, etc... be running. `screenshots` will now use running emus/sims or boot/shutdown new ones as required.

To give it a go:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout dev
pub global activate --source path .
cd <your project>
screenshots
```
Let me know if it works.

**Comment by mmcc007** [comment]
Fixed by #64

**Comment by matthew-carroll** [comment]
Thanks, this solved my issue.

**Comment by mmcc007** [comment]
@matthew-carroll Glad it works.... btw: latest release also works with real devices
