### ISSUE TITLE
Changing locale is not possible if there is only one

### ISSUE THREAD

**Issue by cbenhagen** [mmcc007/screenshots#63]
If you change a single locale in the `screenshots.yaml` it will not be changed in the simulator/emulator because `isMultipleLocales` will be `false`.

Can't we just remove the isMultipleLocales argument of both the simulator and emulator methods and set the locale every time?

**Comment by mmcc007** [comment]
Have not looked into this in a while... will take another look.

**Comment by mmcc007** [comment]
I removed the isMultipleLocales and allowed the test to run in multiple locales (with warning). You should now be able to see how the test fails in a non-default locale for your location and get a stacktrace.

Hopefully this will help narrow down on the problem with flutter driver.

**Comment by mmcc007** [comment]
Fixed by #64
