### ISSUE TITLE
Landscape mode

### ISSUE THREAD

**Issue by cbenhagen** [mmcc007/screenshots#66]
Especially on tablets most app layouts tend to be different in landscape mode. It would be nice to show this in some screenshots.

**Comment by mmcc007** [comment]
To support framing in landscape, would need to set landscape mode, take screenshot, then overlay a status bar and frame. This requires a new set of frames and status bars in landscape (artwork). 
If the artwork can be created/found then it should be possible.

If screenshots are just needed locally for review (not for release to stores), then it may acceptable to skip the framing. 

Which use case are you thinking of, one, the other, or both... or something else?

**Comment by cbenhagen** [comment]
The frame artwork can just be rotated. Status bars would need to be created. Until this is done you could already support unframed versions.

We would maybe use them unframed for stores anyway.

**Comment by mmcc007** [comment]
Duh on the frame rotation... of course. They usually come paired with a status bar, so that threw me off.

Unframed, as currently implemented, has no status bar. So probably not suitable for stores. May split them out with a config option at some point.

**Comment by mmcc007** [comment]
AFAIK, the stores don't provide a landscape option. I think because the store apps run in portrait on devices. So would have to resize the landscape to fit into portrait. Not sure if that's a good look?

**Comment by cbenhagen** [comment]
You can definitely upload screenshots in landscape mode to both Google Play and App Store without needing them to fit in portrait. We already do this.

**Comment by mmcc007** [comment]
Ah, you got me again 😂.. some late nite thinking... ok, thnx.

To avoid problems with subsequent uploading, might be useful to establish some guidelines for which devices landscape is accepted/recommended in stores. A simple guideline to start might be for tablets only. Then get more specific if needed?

**Comment by mmcc007** [comment]
Looked into how to change device orientation and seems to work for android emulators. But could not find how to make it work for ios simulators. Any suggestions?

Have not looked into doing the same for real devices (ios and android). Workaround for real devices might be to handle manually in settings.

**Comment by cbenhagen** [comment]
You can lock the orientation from flutter:
```dart
  SystemChrome.setPreferredOrientations([
      DeviceOrientation.landscapeRight,
      DeviceOrientation.landscapeLeft,
  ]);
```

**Comment by mmcc007** [comment]
> You can lock the orientation from flutter:

For general use case, was trying to avoid dependency on orientation set in app for testing. If there is no practical way to manage orientation at the device/emulator level, do you think requiring the developer to have a version of app tied to landscape for testing is a good way to go ?

**Comment by cbenhagen** [comment]
It would be nice if this was not needed. But it's better than nothing right?

**Comment by mmcc007** [comment]
Found a way to set orientation of iOS simulator using an AppleScript. This requires giving permission to run the script the first time.
Give it a try:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #66_landscape_mode
pub global activate --source path .
cd example
screenshots
```
Let me know if u think applescript is the way to go for orientation on an iOS simulator.

**Comment by mmcc007** [comment]
Currently only works when framing is disabled. Modified no-frame behavior to skip processing status and nav bar. So only get raw screenshot when in landscape.
