### ISSUE TITLE
Support output directory configuration

### ISSUE THREAD

**Issue by matthew-carroll** [mmcc007/screenshots#77]
Currently this library assumes it is being used for fastlane. Therefore, it stores all screenshots in a fastlane directory within each app project.

I'd like to specify an output directory for all screenshots in the `screenshots.yaml` configuration file. My use-case is unrelated to CI.

**Comment by mmcc007** [comment]
If there is nothing specific about your use-case, adding an output directory option to `screenshots.yaml` to output to a directory containing ios and android screenshots should be straightforward enough.

**Comment by matthew-carroll** [comment]
Nothing specific. I'd just like to be able to control where the screenshots go.

**Comment by mmcc007** [comment]
Added an archiving run mode that archives screenshot runs to a directory.
Add to `screenshots.yaml`:
```
archive: /tmp/screenshots_archive
```
Run with:
```
screenshots -m archive
```
Try it out with:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #77_output_dir
pub global activate --source path .
cd example
screenshots -m archive
```
Let me know how it goes.
