### ISSUE TITLE
Add option for transparent background for ios

### ISSUE THREAD

**Issue by Gorniv** [mmcc007/screenshots#81]
I need to create screenshots for a site with a transparent background.
Thank you.

**Comment by mmcc007** [comment]
Screenshots has different run modes, normal, recording, comparison and soon to be released archiving. 

Android screenshots already use a transparent background, Apple over-rides transparent backgrounds in store so Screenshots defaults to a white background for iOS screenshots. 

It might be a good fit to add an option to make iOS background transparent when running in archiving mode.

Would this work for this use-case?

**Comment by Gorniv** [comment]
This work resolves my case.

**Comment by mmcc007** [comment]
OK, cool

**Comment by mmcc007** [comment]
Added transparent background for iOS when archiving. Give it a try:
```
git clone https://github.com/mmcc007/screenshots.git
cd screenshots
git checkout #77_output_dir
pub global activate --source path .
cd example
screenshots -m archive
```
Let me know if this works for this use case.
