### ISSUE TITLE
Run Android emulator in headless mode

### ISSUE THREAD

**Issue by edufolly** [mmcc007/screenshots#91]
An option to run Android emulator in headless mode.

**Comment by mmcc007** [comment]
Thanks for the suggestion. How would you use such an option?

**Comment by edufolly** [comment]
My intent to use this is in Docker to parallelize all emulators in different instances, locally or remotely.
In the screenshots config file, I think the best way to do this is using an option like ```headless: true``` in the Android section.

**Comment by mmcc007** [comment]
_screenshots_ currently requires `adb devices` to find the running emulators.

When running multiple emulators where each individual emulator is run in it's own docker container instance, will `adb devices` still work, or is there another way to discover the running emulators? Can you describe (or provide an example of) how you are setting-up your emulators in docker containers (I assume you are using hardware acceleration)?

BTW: _screenshots_ currently detects if it is running in a CI environment and starts a headless emulator as needed. For example: https://travis-ci.com/mmcc007/screenshots/builds/118862436. The emulator has to be configured correctly for the device it is emulating and startup is slow if running without hardware acceleration. It works on travis (without hardware acceleration).

**Comment by edufolly** [comment]
Hi @mmcc007,

I'll do some tests with docker. I found these cirrus docker images (https://github.com/cirruslabs/docker-images-flutter) to start my research. I'll try to create a parallel pipeline with fastlane, using a docker container to run screenshots into a docker swarm cluster.

Thanks for all.

**Comment by mmcc007** [comment]
Hey @edufolly 

Have used those same docker images in:
https://github.com/brianegan/flutter_architecture_samples
https://github.com/brianegan/flutter_architecture_samples/pull/125

Still requires managing the emulator (preferably with hardware acceleration which is generally not available from CI vendors):
https://github.com/brianegan/flutter_architecture_samples/blob/master/.cirrus.yml

Emulators should work in a swarm of docker containers (preferably with hardware acceleration). But seems still left with issue of how to discover running emulators. 

One possible way to go, which is probably only worthwhile with hardware acceleration, is for _screenshots_ to start the hardware accelerated emulators when needed (when in a custom CI environment, with or without docker).
