### ISSUE TITLE
Not recognizing 'adb'

### ISSUE THREAD

**Issue by SupposedlySam** [mmcc007/screenshots#92]
When attempting to run Screenshots using `flutter pub run screenshots:main` I receive an error stating: "'adb' must be in the PATH to use Screenshots" even though I'm able to type `adb` and get the version and location of its location.

**Comment by mmcc007** [comment]
Thanks for the feedback. You may have an unanticipated config. 

_screenshots_ expects one of:
```
$ANDROID_HOME/platform-tools/adb
$ANDROID_SDK_ROOT/platform-tools/adb
```
to work.

What does
```
which adb
echo $ANDROID_HOME
echo $ANDROID_SDK_ROOT
```
return?

**Comment by SupposedlySam** [comment]
My-MacBook-Pro:responciv JonahWalker$ which adb
/Users/JonahWalker/Library/Android/sdk/platform-tools/adb

My-MacBook-Pro:responciv JonahWalker$ echo $ANDROID_HOME
/Users/JonahWalker/Library/Android/sdk/android-sdk-macosx

My-MacBook-Pro:responciv JonahWalker$ echo $ANDROID_SDK_ROOT

My-MacBook-Pro:responciv JonahWalker$

**Comment by SupposedlySam** [comment]
Ha, I see what I did. You said it is looking to use $ANDROID_HOME/platform-tools/adb but for whatever reason my PATH has the ANDROID_HOME variable set with an extra "/android-sdk-macosx". I removed that and am onto another error. Progress!

**Comment by mmcc007** [comment]
Great!
