### ISSUE TITLE
Changing locale on android emulator: `failed to clear the 'main' log`

### ISSUE THREAD

**Issue by TomEbert** [mmcc007/screenshots#95]
Hi I'd really appreciate some help with this issue since it's kind of deal breaker here and cost me quite some time...

I have everything set accordingly to the README. When running the `screenshots` command in terminal with only an ios device active in the `screenshots.yaml` everything works fine in terms of loading the different localizations and creating the screenshots. But when I run it on an Android Emulator (here: Nexus 6P) and the device locale is not the only entered locale under `locales:` in `screenshots.yaml` the following is the result:

```
Changing locale from en-US to de_DE on 'Nexus 5X'...
failed to clear the 'main' log
Unhandled exception:
command failed: exitcode=1, cmd='adb -s emulator-5556 logcat -c', workingDir=., silent=false
#0      cmd (package:screenshots/src/run.dart:535:5)
#1      waitSysLogMsg (package:screenshots/src/utils.dart:292:3)
<asynchronous suspension>
#2      waitAndroidLocaleChange (package:screenshots/src/utils.dart:246:13)
<asynchronous suspension>
#3      setEmulatorLocale (package:screenshots/src/run.dart:429:11)
<asynchronous suspension>
#4      runTestsOnAll (package:screenshots/src/run.dart:219:17)
<asynchronous suspension>
#5      run (package:screenshots/src/run.dart:64:9)
<asynchronous suspension>
#6      main (file:///Users/tomebert/.pub-cache/hosted/pub.dartlang.org/screenshots-1.3.0/bin/main.dart:85:9)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
```

My `screenshots.yaml` looks like following:
```
# A list of screen capture tests
# Note: flutter driver expects a pair of files eg, main1.dart and main1_test.dart
tests:
  - test_driver/app.dart

# Interim location of screenshots from tests
staging: /tmp/screenshots

# A list of locales supported by the app
locales:
  - en-US
  - de_DE

# A map of devices to emulate
devices:
  ios:
#    iPhone X:
#      frame: true
#    iPad Pro (12.9-inch) (3rd generation):
#      orientation: LandscapeRight
  android:
    Nexus 6P:

# Frame screenshots
frame: true

```
And output of `flutter doctor` is:
```
[✓] Flutter (Channel stable, v1.7.8+hotfix.3, on Mac OS X 10.14.5 18F132, locale en-DE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.3)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] IntelliJ IDEA Ultimate Edition (version 2018.1)
[✓] VS Code (version 1.35.1)
[✓] Connected device (2 available)

• No issues found!
```

Please let me know if I could pass any more information that might help.

**Comment by mmcc007** [comment]
It seems to be finding a `Nexus 5X` when it should be finding `Nexus 6P` (as configured in your screenshots.yaml). It is possible that there is a `Nexus 5X` real device attached or emulator running. 

Try to disconnect or shutdown the `Nexus 5X` and see what happens.

**Comment by TomEbert** [comment]
Hi, sorry for the latency. Closing all my emulator instances and having no real device connected while still having the same `screenshots.yaml` as issued above still results as follows: `Starting flutter daemon...
Clearing images in android/fastlane/metadata/android/en-US/images/phoneScreenshots for 'Nexus 6P'...
Clearing images in android/fastlane/metadata/android/de-DE/images/phoneScreenshots for 'Nexus 6P'...
Starting Nexus 6P...
'Nexus 6P' locale: de-DE, test locale: en-US
Changing locale from de-DE to en-US on 'Nexus 6P'...
failed to clear the 'main' log
Unhandled exception:
command failed: exitcode=1, cmd='adb -s emulator-5554 logcat -c', workingDir=., silent=false
#0      cmd (package:screenshots/src/run.dart:535:5)
#1      waitSysLogMsg (package:screenshots/src/utils.dart:292:3)
<asynchronous suspension>
#2      waitAndroidLocaleChange (package:screenshots/src/utils.dart:246:13)
<asynchronous suspension>
#3      setEmulatorLocale (package:screenshots/src/run.dart:429:11)
<asynchronous suspension>
#4      runTestsOnAll (package:screenshots/src/run.dart:219:17)
<asynchronous suspension>
#5      run (package:screenshots/src/run.dart:64:9)
<asynchronous suspension>
#6      main (file:///Users/tomebert/.pub-cache/hosted/pub.dartlang.org/screenshots-1.3.0/bin/main.dart:85:9)
<asynchronous suspension>
#7      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
#8      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)`

**Comment by TomEbert** [comment]
Additional info that might be interesting: Running `screenshots` works perfectly fine when the `locales` in the `screenshots.yaml` contains **only** the device locale of the android emulator. On iOS devices it works with any number and combination of locales. Maybe thats pointing you in some direction which might be helpful for understanding why it's not working as desired for me.

**Comment by mmcc007** [comment]
I started a `Nexus 6P` emulator:
```
flutter devices
1 connected device:

Android SDK built for x86 • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)
```
and ran the command
```
adb -s emulator-5554 logcat -c
```
without error. 

It might be worth re-installing the `Nexus 6P` using a similar configuration and making sure it is possible to clear the log using above command.

As a diagnostic, if the above command does not work try:
```
adb -s emulator-5554 root
adb -s emulator-5554 logcat -c
```
If giving adb root permission permits clearing the log, there may an unexpected setup issue in your environment.

Hopefully re-installing the `Nexus 6P` will resolve the issue.

**Comment by mmcc007** [comment]
Closing for now. Feel free to provide more info.
