### ISSUE TITLE
Class 'YamlList' has no instance getter 'keys'

### ISSUE THREAD

**Issue by robinbonnes** [mmcc007/screenshots#98]
Using the latest version of Flutter (from master) and latest version of screenshots:

![Schermafbeelding 2019-08-17 om 18 24 47](https://user-images.githubusercontent.com/5117166/63214727-4dcc7200-c11c-11e9-8396-a5e3a58d7f27.png)

**Comment by mmcc007** [comment]
Thanks for the heads-up. 

I tried running on the latest master channel and was not able to reproduce the problem. But noticed some other possible issues. Will wait to see what the upcoming stable releases contain when released.

I removed the dependency on processing objects from the Yaml package. So the above message should not occur in upcoming stable releases.

I upgraded to the latest stable channel (1.7.8+hotfix.4) and it ran fine.

**Comment by robinbonnes** [comment]
Still receiving sort of the same error:

![Schermafbeelding 2019-08-20 om 14 56 55](https://user-images.githubusercontent.com/5117166/63348993-c1f45900-c35a-11e9-9c04-21082b1afab8.png)

This is how my screenshots.yaml file looks like:

```
tests:
  - test_driver/app.dart

staging: /tmp/screenshots

locales:
  - nl-NL

devices:
  ios:
    - iPhone 7 Plus
    - iPhone Xs Max
    - iPad Pro (12.9-inch) (2nd generation)

frame: false
```

**Comment by mmcc007** [comment]
What is your flutter doctor?
